export const enum PERMISSION {
  ALL = 0,
  INVITE = 1,
  ACCEPT_REQUEST = 2,
  REJECT_REQUEST = 3,
  CHANGE_PUBLIC_INFO = 4,
  CHANGE_TERMS = 5,
  CHANGE_ROLES = 6,
  KICK = 7,
  CHANGE_BLACK_LIST = 8,
}
